In [158]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [174]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [175]:
vander = np.vander((np.exp(-1 * 2 * np.pi * 1j * np.arange(a.shape[0]) / a.shape[0])), increasing=True)
sol = vander.dot(a)
sol

array([ 6. +0.00000000e+00j, -2. +2.00000000e+00j, -2. -7.34788079e-16j,
       -2. -2.00000000e+00j])

In [176]:
np.fft.fft(a)

array([ 6.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])

In [180]:
xv, yv = np.meshgrid(a, a)
xv

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [203]:
f1 = vander.dot(xv.dot(vander))
# f1 = f1*0 + np.real_if_close(f1, tol=10000000000000000)
# r = vander.dot(f1)
n = np.around(f1,14)
n

array([[ 24.+0.j,  -8.+8.j,  -8.-0.j,  -8.-8.j],
       [ -0.-0.j,   0.+0.j,   0.+0.j,  -0.+0.j],
       [  0.-0.j,   0.+0.j,  -0.+0.j,  -0.+0.j],
       [  0.-0.j,   0.+0.j,  -0.+0.j,  -0.+0.j]])

In [182]:
np.fft.fft2(xv)

array([[ 24.+0.j,  -8.+8.j,  -8.+0.j,  -8.-8.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j]])