In [263]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.special

In [264]:
a = np.arange(4)
vander = np.vander((np.exp(-1 * 2 * np.pi * 1j * np.arange(a.shape[0]) / a.shape[0])), increasing=True)
np.around(vander.dot(a), 14) - np.fft.fft(a)

array([ 0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j])

In [265]:
xv, yv = np.meshgrid(a, a)
f1 = vander.dot(xv.dot(vander))
np.around(f1, 13) - np.fft.fft2(xv)

array([[ 0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j],
       [-0.-0.j,  0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.-0.j,  0.+0.j, -0.+0.j, -0.+0.j],
       [ 0.-0.j,  0.+0.j, -0.+0.j, -0.+0.j]])

In [329]:
n = 8
c = scipy.special.binom(n, np.arange(n + 1)).astype(np.int64)

c1 = c[:, np.newaxis]
c2 = c[np.newaxis, :]

r = scipy.signal.convolve2d(c1, c2)
r

array([[   1,    8,   28,   56,   70,   56,   28,    8,    1],
       [   8,   64,  224,  448,  560,  448,  224,   64,    8],
       [  28,  224,  784, 1568, 1960, 1568,  784,  224,   28],
       [  56,  448, 1568, 3136, 3920, 3136, 1568,  448,   56],
       [  70,  560, 1960, 3920, 4900, 3920, 1960,  560,   70],
       [  56,  448, 1568, 3136, 3920, 3136, 1568,  448,   56],
       [  28,  224,  784, 1568, 1960, 1568,  784,  224,   28],
       [   8,   64,  224,  448,  560,  448,  224,   64,    8],
       [   1,    8,   28,   56,   70,   56,   28,    8,    1]])

In [341]:
r = r / np.sum(r)
r

array([[  1.52587891e-05,   1.22070312e-04,   4.27246094e-04,
          8.54492188e-04,   1.06811523e-03,   8.54492188e-04,
          4.27246094e-04,   1.22070312e-04,   1.52587891e-05],
       [  1.22070312e-04,   9.76562500e-04,   3.41796875e-03,
          6.83593750e-03,   8.54492188e-03,   6.83593750e-03,
          3.41796875e-03,   9.76562500e-04,   1.22070312e-04],
       [  4.27246094e-04,   3.41796875e-03,   1.19628906e-02,
          2.39257812e-02,   2.99072266e-02,   2.39257812e-02,
          1.19628906e-02,   3.41796875e-03,   4.27246094e-04],
       [  8.54492188e-04,   6.83593750e-03,   2.39257812e-02,
          4.78515625e-02,   5.98144531e-02,   4.78515625e-02,
          2.39257812e-02,   6.83593750e-03,   8.54492188e-04],
       [  1.06811523e-03,   8.54492188e-03,   2.99072266e-02,
          5.98144531e-02,   7.47680664e-02,   5.98144531e-02,
          2.99072266e-02,   8.54492188e-03,   1.06811523e-03],
       [  8.54492188e-04,   6.83593750e-03,   2.39257812e-02,
   

In [342]:
np.sum(r)

1.0

In [362]:
lala = np.random.rand(10,1).shape[0]
lala

10

In [363]:
np.random.rand(10,).shape[0]

10