In [10]:
import numpy as np
from scipy.misc import imread
from skimage.color import rgb2gray
import os

import scipy.special
from scipy.signal import convolve2d

In [21]:
def create_filter_vec(filter_size):

    conv_ker =  np.array([[1, 1]])
    filter = conv_ker

    #  using a O(logN) to compute the filter
    log2 = np.log2(filter_size)
    whole = np.floor(log2).astype(np.int64)
    rest = (filter_size - whole).astype(np.int64)

    for i in range(whole):
        filter = convolve2d(filter, filter).astype(np.float32)
    for i in range(2**rest):
        filter = convolve2d(conv_ker, filter).astype(np.float32)

    # normalize
    # return filter / np.sum(filter)
    return filter

In [25]:
a = create_filter_vec(3)
a

array([[  1.,   6.,  15.,  20.,  15.,   6.,   1.]], dtype=float32)

In [35]:
a = a.reshape([7,1])
a

array([[  1.],
       [  6.],
       [ 15.],
       [ 20.],
       [ 15.],
       [  6.],
       [  1.]], dtype=float32)

In [37]:
np.max([1,2,3])

3

In [38]:
a[::2]

array([[  1.],
       [ 15.],
       [ 15.],
       [  1.]], dtype=float32)

In [39]:
b = [[1,3],[1,4]]
b

[[1, 3], [1, 4]]

In [43]:
b.__len__()

2