In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.special

In [4]:
a = np.arange(4)
vander = np.vander((np.exp(-1 * 2 * np.pi * 1j * np.arange(a.shape[0]) / a.shape[0])), increasing=True)
np.around(vander.dot(a), 14) - np.fft.fft(a)

array([ 0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j])

In [5]:
xv, yv = np.meshgrid(a, a)
f1 = vander.dot(xv.dot(vander))
np.around(f1, 13) - np.fft.fft2(xv)

array([[ 0.+0.j,  0.+0.j,  0.-0.j,  0.+0.j],
       [-0.-0.j,  0.+0.j,  0.+0.j, -0.+0.j],
       [ 0.-0.j,  0.+0.j, -0.+0.j, -0.+0.j],
       [ 0.-0.j,  0.+0.j, -0.+0.j, -0.+0.j]])

In [6]:

bww = np.arange(5)
b,c = np.meshgrid(ww, ww)
b = b[:,0:4]

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [7]:
d = np.array([2,2,2,2,2])
d.shape

(5,)

In [8]:
b.shape

(5, 4)

In [9]:
g, _ = np.meshgrid(np.arange(b.shape[1]), d)
g

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [10]:
b * g

array([[0, 1, 4, 9],
       [0, 1, 4, 9],
       [0, 1, 4, 9],
       [0, 1, 4, 9],
       [0, 1, 4, 9]])

In [11]:
cc = np.array([2,2,2,2])
cc.shape

(4,)

In [12]:
cc * b

array([[0, 2, 4, 6],
       [0, 2, 4, 6],
       [0, 2, 4, 6],
       [0, 2, 4, 6],
       [0, 2, 4, 6]])