In [11]:
import random
import numpy as np
from scipy.misc import imread
from skimage.color import rgb2gray

In [14]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b = a.reshape(1,2,3)
b

array([[[0, 1, 2],
        [3, 4, 5]]])

In [17]:
c = a[np.newaxis]
c

array([[[0, 1, 2],
        [3, 4, 5]]])

In [20]:
corrupted_image = np.array(a).reshape(1, a.shape[0], a.shape[1]) - 0.5
b = corrupted_image[np.newaxis,...]
b

array([[[[-0.5,  0.5,  1.5],
         [ 2.5,  3.5,  4.5]]]])

In [21]:
c = (a[np.newaxis] - 0.5)[np.newaxis]
c

array([[[[-0.5,  0.5,  1.5],
         [ 2.5,  3.5,  4.5]]]])

In [22]:
d = a[np.newaxis][np.newaxis] - 0.5
d

array([[[[-0.5,  0.5,  1.5],
         [ 2.5,  3.5,  4.5]]]])

In [23]:
e = a[np.newaxis, np.newaxis] - 0.5
e

array([[[[-0.5,  0.5,  1.5],
         [ 2.5,  3.5,  4.5]]]])