In [2]:
import numpy as np
import scipy.special
from scipy.signal import convolve2d

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,1]])
c = convolve2d(a,b,mode='same')
c

array([[ 1,  3,  5],
       [ 4,  9, 11],
       [ 7, 15, 17]])

In [4]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [5]:
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [6]:
np.array([a,a])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
np.array(list(map(np.square, np.array([[a,a],[a,a]]))))

array([[[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]],

        [[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]],


       [[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]],

        [[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]]])

In [8]:
from scipy import ndimage
a = np.arange(12.).reshape((4, 3))
a

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [22]:
ndimage.map_coordinates(a, [[0,0],[1,2]], order=1, prefilter=False)

array([ 1.,  2.])

In [20]:
ndimage.map_coordinates(a, [[0,0],[1,1]], order=1, prefilter=False)

array([ 1.,  1.])