In [5]:
import numpy as np
import scipy.special
from scipy.signal import convolve2d

In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,1]])
c = convolve2d(a,b,mode='same')
c

array([[1, 3],
       [3, 7]])

In [8]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [9]:
np.square(a)

array([[ 1,  4],
       [ 9, 16]])

In [11]:
np.array([a,a])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [16]:
np.array(list(map(np.square,np.array([a,a]))))

array([[[ 1,  4],
        [ 9, 16]],

       [[ 1,  4],
        [ 9, 16]]])